Raise a more graceful error when fields are None
Currently, whenever fields in Jira tickets are not being filled-in (e.g.
user / email domain fields), we get the following error:
```
Traceback (most recent call last):
  File
"/home/assisted-installer-deployment/./tools/triage_status_report.py",
line 89, in <module>
    main()
  File
"/home/assisted-installer-deployment/./tools/triage_status_report.py",
line 85, in main
    triage_status_report(client, args.filter_id, args.webhook)
  File
"/home/assisted-installer-deployment/./tools/triage_status_report.py",
line 65, in triage_status_report
    for issue in sorted(_get_issues_data(issues)):
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

Error is very hard to understand, so this change aims to validate fields
before dataclass logic for comparison actions tries to compare None
value with strings.