Fix wrong `tools/create_triage_tickets.py` parameter (#252)
The fix in 0eaec1d4103379af72c046cc01ca03939e7436b9 was invalid,
it passed the wrong parameter, which caused:

http://assisted-jenkins.usersys.redhat.com/job/download_logs/37113/console

```
17:24:48  Traceback (most recent call last):
17:24:48    File "/mnt-assisted-log/workspace/download_logs/assisted-installer-deployment/./tools/create_triage_tickets.py", line 174, in <module>
17:24:48      main(args)
17:24:48    File "<decorator-gen-4>", line 2, in main
17:24:48    File "/usr/local/lib/python3.9/site-packages/retry/api.py", line 73, in retry_decorator
17:24:48      return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
17:24:48    File "/usr/local/lib/python3.9/site-packages/retry/api.py", line 33, in __retry_internal
17:24:48      return f()
17:24:48    File "/mnt-assisted-log/workspace/download_logs/assisted-installer-deployment/./tools/create_triage_tickets.py", line 130, in main
17:24:48      process_ticket_with_signatures(
17:24:48  TypeError: process_ticket_with_signatures() missing 1 required positional argument: 'dry_run_file'
```

This commit should fix it